// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lys-app-redesign/Dashboard.tsx": () => import("../components/mockups/lys-app-redesign/Dashboard.tsx"),
  "./components/mockups/landing-variants/LiveDemo.tsx": () => import("../components/mockups/landing-variants/LiveDemo.tsx"),
  "./components/mockups/landing-variants/OutcomeProof.tsx": () => import("../components/mockups/landing-variants/OutcomeProof.tsx"),
  "./components/mockups/landing-variants/RoleRouted.tsx": () => import("../components/mockups/landing-variants/RoleRouted.tsx"),
  "./components/mockups/landing-variants/ToolFirst.tsx": () => import("../components/mockups/landing-variants/ToolFirst.tsx"),
  "./components/mockups/onboarding-flow/FirstValue.tsx": () => import("../components/mockups/onboarding-flow/FirstValue.tsx"),
  "./components/mockups/onboarding-flow/Home.tsx": () => import("../components/mockups/onboarding-flow/Home.tsx"),
  "./components/mockups/onboarding-flow/Landing.tsx": () => import("../components/mockups/onboarding-flow/Landing.tsx"),
  "./components/mockups/onboarding-flow/Setup.tsx": () => import("../components/mockups/onboarding-flow/Setup.tsx"),
  "./components/mockups/sidebar-redesign/BeKnowDoEditorial.tsx": () => import("../components/mockups/sidebar-redesign/BeKnowDoEditorial.tsx"),
  "./components/mockups/sidebar-redesign/IconRailAdaptive.tsx": () => import("../components/mockups/sidebar-redesign/IconRailAdaptive.tsx"),
  "./components/mockups/sidebar-redesign/IconRailCharcoal.tsx": () => import("../components/mockups/sidebar-redesign/IconRailCharcoal.tsx"),
  "./components/mockups/sidebar-redesign/IconRailFlyout.tsx": () => import("../components/mockups/sidebar-redesign/IconRailFlyout.tsx"),
  "./components/mockups/sidebar-redesign/IconRailFlyoutRefinedA.tsx": () => import("../components/mockups/sidebar-redesign/IconRailFlyoutRefinedA.tsx"),
  "./components/mockups/sidebar-redesign/IconRailFlyoutRefinedB.tsx": () => import("../components/mockups/sidebar-redesign/IconRailFlyoutRefinedB.tsx"),
  "./components/mockups/sidebar-redesign/IconRailSunlit.tsx": () => import("../components/mockups/sidebar-redesign/IconRailSunlit.tsx"),
  "./components/mockups/sidebar-redesign/PinnedFavorites.tsx": () => import("../components/mockups/sidebar-redesign/PinnedFavorites.tsx"),
  "./components/mockups/sidebar-redesign/ThreeZones.tsx": () => import("../components/mockups/sidebar-redesign/ThreeZones.tsx"),
  "./components/mockups/sidebar-redesign/ThreeZonesRefinedA.tsx": () => import("../components/mockups/sidebar-redesign/ThreeZonesRefinedA.tsx"),
  "./components/mockups/sidebar-redesign/ThreeZonesRefinedB.tsx": () => import("../components/mockups/sidebar-redesign/ThreeZonesRefinedB.tsx"),
  "./components/mockups/student-merge/MenuBeforeAfter.tsx": () => import("../components/mockups/student-merge/MenuBeforeAfter.tsx"),
  "./components/mockups/student-merge/UnifiedStudentPage.tsx": () => import("../components/mockups/student-merge/UnifiedStudentPage.tsx")
};
