// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/student-merge/MenuBeforeAfter.tsx": () => import("../components/mockups/student-merge/MenuBeforeAfter.tsx"),
  "./components/mockups/student-merge/UnifiedStudentPage.tsx": () => import("../components/mockups/student-merge/UnifiedStudentPage.tsx")
};
