// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboarding-flow/FirstValue.tsx": () => import("../components/mockups/onboarding-flow/FirstValue.tsx"),
  "./components/mockups/onboarding-flow/Home.tsx": () => import("../components/mockups/onboarding-flow/Home.tsx"),
  "./components/mockups/onboarding-flow/Landing.tsx": () => import("../components/mockups/onboarding-flow/Landing.tsx"),
  "./components/mockups/onboarding-flow/Setup.tsx": () => import("../components/mockups/onboarding-flow/Setup.tsx"),
  "./components/mockups/student-merge/MenuBeforeAfter.tsx": () => import("../components/mockups/student-merge/MenuBeforeAfter.tsx"),
  "./components/mockups/student-merge/UnifiedStudentPage.tsx": () => import("../components/mockups/student-merge/UnifiedStudentPage.tsx")
};
