import { db } from "../db";
import { knowResources, scholarshipSyncLog } from "../../shared/schema";
import { eq, and, or, isNull, lt } from "drizzle-orm";

// ─── Seed Data ───────────────────────────────────────────────────────────────
// 50+ real, well-known scholarships across categories, states, and demographics

const SEED_SCHOLARSHIPS = [
  {
    title: "Gates Millennium Scholars Program",
    description: "Provides outstanding minority students with financial support through undergraduate and graduate school in any discipline they choose.",
    url: "https://gmsp.org",
    applicationUrl: "https://gmsp.org/overview/",
    scholarshipType: "both",
    scholarshipAmount: "Full cost of attendance",
    scholarshipDeadline: "January 15",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.3+",
    minGpaDecimal: 3.3,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["African American, American Indian/Alaska Native, Asian Pacific Islander, or Hispanic", "High school senior", "US citizen or permanent resident", "Min 3.3 GPA", "Demonstrated financial need"],
    careerFields: ["STEM", "Education", "Library Science", "Public Health", "Mathematics"],
    stateRestrictions: [],
    tags: ["minority", "full-ride", "graduate", "undergraduate", "prestigious"],
    category: "General",
  },
  {
    title: "QuestBridge National College Match",
    description: "Connects outstanding low-income high school seniors with full four-year scholarships to the nation's best colleges.",
    url: "https://www.questbridge.org",
    applicationUrl: "https://www.questbridge.org/high-school-students/national-college-match",
    scholarshipType: "both",
    scholarshipAmount: "Full scholarship (tuition, room & board, books)",
    scholarshipDeadline: "September 26",
    scholarshipSeason: "early_fall",
    gpaRequirement: "3.5+",
    minGpaDecimal: 3.5,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["High school senior", "Low-income background", "Exceptional academic achievement", "US citizen or permanent resident"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["full-ride", "need-based", "low-income", "prestigious"],
    category: "General",
  },
  {
    title: "Jack Kent Cooke Foundation College Scholarship",
    description: "Supports high-achieving students with financial need from 8th grade through post-baccalaureate study.",
    url: "https://www.jkcf.org",
    applicationUrl: "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
    scholarshipType: "both",
    scholarshipAmount: "Up to $55,000 per year",
    scholarshipDeadline: "November 1",
    scholarshipSeason: "early_fall",
    gpaRequirement: "3.5+",
    minGpaDecimal: 3.5,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["High school senior", "Unmet financial need", "Academic excellence", "Leadership", "Commitment to serve others"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["need-based", "leadership", "prestigious", "renewable"],
    category: "General",
  },
  {
    title: "Coca-Cola Scholars Program",
    description: "One of the most prestigious merit-based college scholarships, awarded to high school seniors across the country.",
    url: "https://www.coca-colascholarsfoundation.org",
    applicationUrl: "https://www.coca-colascholarsfoundation.org/apply/",
    scholarshipType: "merit",
    scholarshipAmount: "$20,000",
    scholarshipDeadline: "October 31",
    scholarshipSeason: "early_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "high_school",
    firstGenFriendly: false,
    isRecurring: true,
    eligibilityCriteria: ["High school senior", "US citizen, permanent resident, or DACA", "Min 3.0 GPA", "Community leadership"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["merit", "leadership", "community-service", "prestigious"],
    category: "General",
  },
  {
    title: "Dell Scholars Program",
    description: "Supports motivated students who need more than just financial assistance to complete their college education.",
    url: "https://www.dellscholars.org",
    applicationUrl: "https://www.dellscholars.org/scholarship/",
    scholarshipType: "both",
    scholarshipAmount: "$20,000 + laptop + resources",
    scholarshipDeadline: "December 1",
    scholarshipSeason: "late_fall",
    gpaRequirement: "2.4+",
    minGpaDecimal: 2.4,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: false,
    eligibilityCriteria: ["High school senior", "Participating in approved college-readiness program", "Financial need", "Min 2.4 GPA"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["need-based", "first-gen", "technology", "support-services"],
    category: "General",
  },
  {
    title: "Ron Brown Scholar Program",
    description: "Selects African American high school seniors who have demonstrated academic excellence, leadership, and community service.",
    url: "https://www.ronbrown.org",
    applicationUrl: "https://www.ronbrown.org/apply",
    scholarshipType: "both",
    scholarshipAmount: "$40,000 ($10,000/year)",
    scholarshipDeadline: "January 9",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["African American", "High school senior", "US citizen or permanent resident", "Financial need", "Community leadership"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["African-American", "need-based", "leadership", "community-service"],
    category: "General",
  },
  {
    title: "Hispanic Scholarship Fund",
    description: "The nation's largest nonprofit organization supporting Hispanic American higher education.",
    url: "https://www.hsf.net",
    applicationUrl: "https://www.hsf.net/scholarship",
    scholarshipType: "both",
    scholarshipAmount: "$500–$5,000",
    scholarshipDeadline: "February 15",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Hispanic heritage", "US citizen, permanent resident, or DACA", "Min 3.0 GPA", "Enrolled or plan to enroll in college"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["Hispanic", "Latino", "minority", "renewable"],
    category: "General",
  },
  {
    title: "United Negro College Fund (UNCF) Scholarships",
    description: "Provides scholarships, internships, and fellowships to African American students at UNCF member institutions and other colleges.",
    url: "https://uncf.org",
    applicationUrl: "https://uncf.org/scholarships",
    scholarshipType: "both",
    scholarshipAmount: "Varies",
    scholarshipDeadline: "Varies by program",
    scholarshipSeason: "early_fall",
    gpaRequirement: "2.5+",
    minGpaDecimal: 2.5,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["African American", "US citizen", "Financial need", "Enrolled in accredited college/university"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["African-American", "HBCU", "need-based", "multiple-programs"],
    category: "General",
  },
  {
    title: "Thurgood Marshall College Fund Scholarship",
    description: "Supports high-achieving students attending publicly supported HBCUs and predominantly Black institutions.",
    url: "https://www.thurgoodmarshallfund.net",
    applicationUrl: "https://www.thurgoodmarshallfund.net/scholarships-a-fellowships",
    scholarshipType: "both",
    scholarshipAmount: "Up to $6,000",
    scholarshipDeadline: "April 26",
    scholarshipSeason: "early_spring",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Attending TMCF member school (HBCU or PBI)", "Full-time student", "Min 3.0 GPA", "Financial need"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["HBCU", "African-American", "need-based"],
    category: "General",
  },
  {
    title: "Asian Pacific Islander Americans Scholarship Fund (APIASF)",
    description: "Provides college scholarships to low-income Asian American and Pacific Islander students.",
    url: "https://www.apiasf.org",
    applicationUrl: "https://www.apiasf.org/scholarship_apiasf.html",
    scholarshipType: "both",
    scholarshipAmount: "Up to $20,000",
    scholarshipDeadline: "January 10",
    scholarshipSeason: "late_fall",
    gpaRequirement: "2.7+",
    minGpaDecimal: 2.7,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: false,
    eligibilityCriteria: ["Asian American or Pacific Islander heritage", "US citizen, national, or permanent resident", "Min 2.7 GPA", "Financial need"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["Asian-American", "Pacific-Islander", "need-based", "minority"],
    category: "General",
  },
  {
    title: "American Indian College Fund Scholarship",
    description: "Provides scholarships to American Indian and Alaska Native students attending tribal colleges and universities.",
    url: "https://collegefund.org",
    applicationUrl: "https://collegefund.org/students/scholarships/",
    scholarshipType: "both",
    scholarshipAmount: "Varies",
    scholarshipDeadline: "May 31",
    scholarshipSeason: "early_spring",
    gpaRequirement: "2.0+",
    minGpaDecimal: 2.0,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Enrolled member of federally recognized tribe", "Attending tribal college or mainstream university", "Financial need"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["Native-American", "Indigenous", "tribal-college", "need-based"],
    category: "General",
  },
  {
    title: "National Merit Scholarship",
    description: "A prestigious academic competition for recognition and college scholarships, based on PSAT/NMSQT scores.",
    url: "https://www.nationalmerit.org",
    applicationUrl: "https://www.nationalmerit.org/s/1758/interior.aspx?sid=1758&gid=2&pgid=424",
    scholarshipType: "merit",
    scholarshipAmount: "$2,500",
    scholarshipDeadline: "PSAT in October (junior year)",
    scholarshipSeason: "early_fall",
    gpaRequirement: "3.5+",
    minGpaDecimal: 3.5,
    studentLevel: "high_school",
    firstGenFriendly: false,
    isRecurring: false,
    eligibilityCriteria: ["High school junior", "US citizen", "High PSAT/NMSQT score", "Full-time high school student"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["merit", "PSAT", "competitive", "prestigious"],
    category: "General",
  },
  {
    title: "Elks National Foundation Most Valuable Student Scholarship",
    description: "Awarded to high school seniors based on scholarship, leadership, and financial need.",
    url: "https://www.elks.org/scholars/",
    applicationUrl: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    scholarshipType: "both",
    scholarshipAmount: "Up to $12,500/year (4 years)",
    scholarshipDeadline: "November 5",
    scholarshipSeason: "early_fall",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "high_school",
    firstGenFriendly: false,
    isRecurring: true,
    eligibilityCriteria: ["High school senior", "US citizen", "Financial need", "Leadership"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["leadership", "need-based", "merit", "renewable"],
    category: "General",
  },
  {
    title: "Horatio Alger Association Scholarship",
    description: "Assists high school students who have faced and overcome great obstacles in their young lives.",
    url: "https://horatioalger.org",
    applicationUrl: "https://horatioalger.org/scholarships/",
    scholarshipType: "both",
    scholarshipAmount: "$25,000",
    scholarshipDeadline: "October 25",
    scholarshipSeason: "early_fall",
    gpaRequirement: "2.0+",
    minGpaDecimal: 2.0,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: false,
    eligibilityCriteria: ["High school senior", "Significant financial need", "Overcome adversity", "Min 2.0 GPA", "US citizen or permanent resident", "Community involvement"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["need-based", "adversity", "community-service"],
    category: "General",
  },
  {
    title: "Burger King Scholars Program",
    description: "Provides scholarships to high school seniors who are Burger King employees, their family members, or general high school seniors.",
    url: "https://www.bkmclamorefoundation.org",
    applicationUrl: "https://www.scholarshipamerica.org/burgerkingscholars/",
    scholarshipType: "both",
    scholarshipAmount: "$1,000–$50,000",
    scholarshipDeadline: "December 15",
    scholarshipSeason: "late_fall",
    gpaRequirement: "2.5+",
    minGpaDecimal: 2.5,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: false,
    eligibilityCriteria: ["High school senior", "Min 2.5 GPA", "Financial need", "Part-time employment"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["employee", "work-experience", "need-based"],
    category: "General",
  },
  {
    title: "Google Lime Scholarship",
    description: "Supporting students with visible and invisible disabilities pursuing degrees in computer science and related fields.",
    url: "https://buildyourfuture.withgoogle.com/scholarships/lime-scholarship",
    applicationUrl: "https://buildyourfuture.withgoogle.com/scholarships/lime-scholarship",
    scholarshipType: "merit",
    scholarshipAmount: "$10,000",
    scholarshipDeadline: "December 1",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "undergraduate",
    firstGenFriendly: false,
    isRecurring: true,
    eligibilityCriteria: ["Undergraduate or graduate student", "Computer Science or related major", "Disability (visible or invisible)", "Min 3.0 GPA"],
    careerFields: ["Technology", "Computer Science", "Engineering"],
    stateRestrictions: [],
    tags: ["disability", "STEM", "technology", "Google"],
    category: "STEM",
  },
  {
    title: "Generation Google Scholarship",
    description: "Supporting students who are historically underrepresented in tech through financial and community resources.",
    url: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship",
    applicationUrl: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship",
    scholarshipType: "merit",
    scholarshipAmount: "$10,000",
    scholarshipDeadline: "December 1",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.2+",
    minGpaDecimal: 3.2,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Undergraduate freshman through junior", "Computer Science or related major", "Underrepresented in tech", "Min 3.2 GPA"],
    careerFields: ["Technology", "Computer Science", "Engineering"],
    stateRestrictions: [],
    tags: ["diversity", "STEM", "technology", "Google", "underrepresented"],
    category: "STEM",
  },
  {
    title: "Society of Women Engineers Scholarship",
    description: "Provides financial assistance to women pursuing undergraduate and graduate degrees in engineering and computer science.",
    url: "https://scholarships.swe.org",
    applicationUrl: "https://scholarships.swe.org/applications/login.asp",
    scholarshipType: "merit",
    scholarshipAmount: "$1,000–$15,000",
    scholarshipDeadline: "February 15",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Women identifying students", "Engineering or Computer Science major", "Min 3.0 GPA", "Full-time student"],
    careerFields: ["Engineering", "Technology", "Computer Science"],
    stateRestrictions: [],
    tags: ["women", "engineering", "STEM", "renewable"],
    category: "Engineering",
  },
  {
    title: "Barry Goldwater Scholarship",
    description: "Premier undergraduate award for students pursuing careers in mathematics, the natural sciences, and engineering.",
    url: "https://goldwaterscholarship.gov",
    applicationUrl: "https://goldwaterscholarship.gov/apply/",
    scholarshipType: "merit",
    scholarshipAmount: "$7,500",
    scholarshipDeadline: "January (institution deadline)",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.8+",
    minGpaDecimal: 3.8,
    studentLevel: "undergraduate",
    firstGenFriendly: false,
    isRecurring: true,
    eligibilityCriteria: ["Sophomore or junior undergrad", "STEM major", "US citizen or permanent resident", "Plans to pursue research career"],
    careerFields: ["STEM", "Research", "Mathematics", "Engineering", "Natural Sciences"],
    stateRestrictions: [],
    tags: ["research", "STEM", "prestigious", "merit"],
    category: "STEM",
  },
  {
    title: "TEACH Grant",
    description: "Provides grants of up to $4,000/year to students completing coursework needed to begin a career in teaching.",
    url: "https://studentaid.gov/understand-aid/types/grants/teach",
    applicationUrl: "https://studentaid.gov/understand-aid/types/grants/teach",
    scholarshipType: "both",
    scholarshipAmount: "Up to $4,000/year",
    scholarshipDeadline: "Ongoing (FAFSA required)",
    scholarshipSeason: "early_spring",
    gpaRequirement: "3.25+",
    minGpaDecimal: 3.25,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Education major", "Min 3.25 GPA or high test scores", "Agree to teach high-need field in low-income school for 4 years", "FAFSA required"],
    careerFields: ["Education", "Teaching"],
    stateRestrictions: [],
    tags: ["education", "teaching", "federal", "service-commitment"],
    category: "Education",
  },
  {
    title: "National Health Service Corps Scholarship",
    description: "Provides scholarships to students pursuing primary health care careers who commit to serving in underserved areas.",
    url: "https://nhsc.hrsa.gov/scholarships",
    applicationUrl: "https://nhsc.hrsa.gov/scholarships",
    scholarshipType: "both",
    scholarshipAmount: "Full tuition + stipend (~$1,400/month)",
    scholarshipDeadline: "March",
    scholarshipSeason: "early_spring",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "graduate",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["US citizen or national", "Enrolled in accredited health professions program", "Commit to service in NHSC-approved site", "Primary care focus"],
    careerFields: ["Healthcare", "Medicine", "Nursing", "Dentistry"],
    stateRestrictions: [],
    tags: ["healthcare", "federal", "service-commitment", "full-ride"],
    category: "Healthcare",
  },
  {
    title: "Chick-fil-A Remarkable Futures Scholarship",
    description: "Awarded to Chick-fil-A Team Members pursuing higher education in any field of study.",
    url: "https://www.chick-fil-a.com/remarkable-futures",
    applicationUrl: "https://www.chick-fil-a.com/remarkable-futures",
    scholarshipType: "both",
    scholarshipAmount: "$1,000–$25,000",
    scholarshipDeadline: "February",
    scholarshipSeason: "late_fall",
    gpaRequirement: "2.5+",
    minGpaDecimal: 2.5,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Chick-fil-A Team Member", "Min 2.5 GPA", "Part-time or full-time employee"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["employee", "food-service", "work-experience"],
    category: "General",
  },
  {
    title: "Discover Scholarship Program",
    description: "Supporting first-generation and community college students through financial aid and mentorship.",
    url: "https://www.discover.com/credit-cards/member-benefits/scholarship.html",
    applicationUrl: "https://www.discover.com/credit-cards/member-benefits/scholarship.html",
    scholarshipType: "both",
    scholarshipAmount: "$25,000",
    scholarshipDeadline: "January",
    scholarshipSeason: "late_fall",
    gpaRequirement: "2.75+",
    minGpaDecimal: 2.75,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: false,
    eligibilityCriteria: ["First-generation college student or community college transfer", "US citizen", "Financial need", "Min 2.75 GPA"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["first-gen", "community-college", "need-based"],
    category: "General",
  },
  {
    title: "Scholarships for Military Children",
    description: "Provides college scholarships to the dependent children of military servicemembers.",
    url: "https://www.militaryscholar.org",
    applicationUrl: "https://www.militaryscholar.org/sfmc/index.html",
    scholarshipType: "merit",
    scholarshipAmount: "$2,000",
    scholarshipDeadline: "February 23",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "high_school",
    firstGenFriendly: false,
    isRecurring: true,
    eligibilityCriteria: ["Dependent child of active duty, Guard, or Reserve servicemember", "High school senior", "Min 3.0 GPA", "Commissary shopper"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["military", "dependent", "merit"],
    category: "General",
  },
  {
    title: "American Chemical Society Scholars Program",
    description: "Provides renewable scholarships to underrepresented minority students majoring in chemistry-related disciplines.",
    url: "https://www.acs.org/education/students/college/scholarships.html",
    applicationUrl: "https://www.acs.org/education/students/college/scholarships.html",
    scholarshipType: "both",
    scholarshipAmount: "Up to $5,000",
    scholarshipDeadline: "March 1",
    scholarshipSeason: "early_spring",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["African American, Hispanic, or American Indian", "Chemistry or related major", "Min 3.0 GPA", "Financial need", "US citizen or permanent resident"],
    careerFields: ["STEM", "Chemistry", "Science", "Research"],
    stateRestrictions: [],
    tags: ["chemistry", "STEM", "minority", "renewable"],
    category: "STEM",
  },
  {
    title: "AFCEA STEM Scholarship",
    description: "Supports US students pursuing science, technology, engineering, and mathematics degrees.",
    url: "https://www.afcea.org/site/foundation/scholarships",
    applicationUrl: "https://www.afcea.org/site/foundation/scholarships",
    scholarshipType: "merit",
    scholarshipAmount: "$2,500–$5,000",
    scholarshipDeadline: "February 1",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "undergraduate",
    firstGenFriendly: false,
    isRecurring: true,
    eligibilityCriteria: ["US citizen", "STEM major (specifically cyber security, intelligence, or related)", "Min 3.0 GPA", "Full-time student", "Junior or senior undergraduate"],
    careerFields: ["Technology", "Engineering", "STEM", "Cybersecurity"],
    stateRestrictions: [],
    tags: ["STEM", "cybersecurity", "military-adjacent", "technology"],
    category: "STEM",
  },
  {
    title: "Texas Public Educational Grant (TPEG)",
    description: "Provides need-based financial assistance to Texas residents attending Texas public institutions.",
    url: "https://www.highered.texas.gov",
    applicationUrl: "https://www.highered.texas.gov/student-success/student-financial-aid/types-of-financial-aid/grants/",
    scholarshipType: "both",
    scholarshipAmount: "Varies",
    scholarshipDeadline: "Varies (FAFSA required)",
    scholarshipSeason: "early_spring",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Texas resident", "Attending Texas public institution", "Financial need", "FAFSA required"],
    careerFields: [],
    stateRestrictions: ["TX"],
    tags: ["Texas", "state-grant", "need-based"],
    category: "General",
  },
  {
    title: "Florida Bright Futures Scholarship",
    description: "Rewarding Florida high school graduates for their academic achievements and public service.",
    url: "https://www.floridastudentfinancialaidsg.org",
    applicationUrl: "https://www.floridastudentfinancialaidsg.org/PDF/FBF_FactSheet.pdf",
    scholarshipType: "merit",
    scholarshipAmount: "75%–100% tuition",
    scholarshipDeadline: "Apply with Florida Financial Aid Application",
    scholarshipSeason: "early_spring",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "high_school",
    firstGenFriendly: false,
    isRecurring: true,
    eligibilityCriteria: ["Florida resident", "Florida high school graduate", "Min 3.0 GPA", "Community service hours", "Eligible SAT/ACT scores"],
    careerFields: [],
    stateRestrictions: ["FL"],
    tags: ["Florida", "state-scholarship", "merit", "tuition-waiver"],
    category: "General",
  },
  {
    title: "California Cal Grant",
    description: "California's primary need-based state grant program for students attending California colleges.",
    url: "https://www.csac.ca.gov/cal-grants",
    applicationUrl: "https://www.csac.ca.gov/cal-grants",
    scholarshipType: "both",
    scholarshipAmount: "Up to $12,570/year",
    scholarshipDeadline: "March 2",
    scholarshipSeason: "early_spring",
    gpaRequirement: "2.0–3.0+ (depends on type)",
    minGpaDecimal: 2.0,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["California resident", "US citizen or eligible noncitizen", "Financial need", "FAFSA or CA Dream Act required"],
    careerFields: [],
    stateRestrictions: ["CA"],
    tags: ["California", "state-grant", "need-based", "renewable"],
    category: "General",
  },
  {
    title: "New York State Tuition Assistance Program (TAP)",
    description: "Helps eligible New York residents pay tuition at approved schools in New York State.",
    url: "https://www.hesc.ny.gov/pay-for-college/financial-aid/types-of-financial-aid/nys-grants-scholarships-awards/tap.html",
    applicationUrl: "https://www.hesc.ny.gov/pay-for-college/financial-aid/types-of-financial-aid/nys-grants-scholarships-awards/tap.html",
    scholarshipType: "both",
    scholarshipAmount: "Up to $5,665",
    scholarshipDeadline: "Ongoing (FAFSA + TAP required)",
    scholarshipSeason: "early_spring",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["New York State resident", "Attending approved NY school", "US citizen or eligible noncitizen", "Financial need"],
    careerFields: [],
    stateRestrictions: ["NY"],
    tags: ["New York", "state-grant", "need-based", "tuition"],
    category: "General",
  },
  {
    title: "Excel Award (Texas)",
    description: "Assists Texas residents with exceptional financial need attending public and private institutions.",
    url: "https://www.highered.texas.gov",
    applicationUrl: "https://www.highered.texas.gov/student-success/student-financial-aid/types-of-financial-aid/grants/",
    scholarshipType: "both",
    scholarshipAmount: "Up to $5,000",
    scholarshipDeadline: "Varies by institution",
    scholarshipSeason: "early_spring",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Texas resident", "Exceptional financial need", "FAFSA required"],
    careerFields: [],
    stateRestrictions: ["TX"],
    tags: ["Texas", "state-grant", "exceptional-need"],
    category: "General",
  },
  {
    title: "LULAC National Scholarship Fund",
    description: "Provides scholarships to Hispanic students demonstrating academic achievement, financial need, and community service.",
    url: "https://www.lulac.org/programs/education/scholarships/",
    applicationUrl: "https://www.lulac.org/programs/education/scholarships/",
    scholarshipType: "both",
    scholarshipAmount: "$250–$2,000",
    scholarshipDeadline: "March 31",
    scholarshipSeason: "early_spring",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Hispanic heritage", "US citizen or legal resident", "Min 3.0 GPA", "Financial need", "Community service"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["Hispanic", "Latino", "community-service", "need-based"],
    category: "General",
  },
  {
    title: "Scholarships360 Scholarship",
    description: "Open to students of all backgrounds committed to making a difference through education.",
    url: "https://scholarships360.org/scholarships/scholarships360-scholarship/",
    applicationUrl: "https://scholarships360.org/scholarships/scholarships360-scholarship/",
    scholarshipType: "merit",
    scholarshipAmount: "$1,000",
    scholarshipDeadline: "Monthly",
    scholarshipSeason: "early_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["US citizen or permanent resident", "Min 3.0 GPA", "Enrolled or plan to enroll in college"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["accessible", "monthly", "general", "easy-apply"],
    category: "General",
  },
  {
    title: "Nursing Scholarship Program (HRSA)",
    description: "Provides scholarships for nursing students who agree to work in eligible health care facilities serving underserved populations.",
    url: "https://bhw.hrsa.gov/funding/apply-scholarships/nursing-scholarship",
    applicationUrl: "https://bhw.hrsa.gov/funding/apply-scholarships/nursing-scholarship",
    scholarshipType: "both",
    scholarshipAmount: "Full tuition + living stipend",
    scholarshipDeadline: "May",
    scholarshipSeason: "early_spring",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Enrolled in accredited nursing program", "US citizen or national", "Commit to 2+ years of service at eligible site"],
    careerFields: ["Healthcare", "Nursing"],
    stateRestrictions: [],
    tags: ["nursing", "healthcare", "federal", "service-commitment", "full-ride"],
    category: "Healthcare",
  },
  {
    title: "American Association of University Women (AAUW) Scholarships",
    description: "Empowers women in higher education through fellowships, grants, and research support.",
    url: "https://www.aauw.org/resources/programs/fellowships-grants/",
    applicationUrl: "https://www.aauw.org/resources/programs/fellowships-grants/",
    scholarshipType: "merit",
    scholarshipAmount: "$2,000–$30,000",
    scholarshipDeadline: "November–January",
    scholarshipSeason: "late_fall",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Women or nonbinary students", "US citizen or permanent resident", "Enrolled in accredited college/university"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["women", "gender-equity", "graduate", "undergraduate", "research"],
    category: "General",
  },
  {
    title: "SkillsUSA Scholarships",
    description: "Provides scholarships to SkillsUSA members pursuing career and technical education.",
    url: "https://www.skillsusa.org/programs/scholarships/",
    applicationUrl: "https://www.skillsusa.org/programs/scholarships/",
    scholarshipType: "merit",
    scholarshipAmount: "$1,000–$5,000",
    scholarshipDeadline: "February",
    scholarshipSeason: "late_fall",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Active SkillsUSA member", "Career and technical education student", "Community involvement"],
    careerFields: ["Trades", "Technology", "Healthcare", "Engineering"],
    stateRestrictions: [],
    tags: ["CTE", "vocational", "trade", "technical"],
    category: "Vocational",
  },
  {
    title: "Future Business Leaders of America (FBLA) Scholarships",
    description: "Supports students pursuing careers in business-related disciplines.",
    url: "https://www.fbla.org/divisions/fbla/fbla-scholarships/",
    applicationUrl: "https://www.fbla.org/divisions/fbla/fbla-scholarships/",
    scholarshipType: "merit",
    scholarshipAmount: "$500–$12,000",
    scholarshipDeadline: "April",
    scholarshipSeason: "early_spring",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "high_school",
    firstGenFriendly: false,
    isRecurring: true,
    eligibilityCriteria: ["Active FBLA member", "Business-related major", "Min 3.0 GPA", "Community service"],
    careerFields: ["Business", "Finance", "Entrepreneurship", "Marketing"],
    stateRestrictions: [],
    tags: ["business", "leadership", "FBLA", "merit"],
    category: "Business",
  },
  {
    title: "National FFA Organization Scholarships",
    description: "Awards scholarships to FFA members and agricultural education students pursuing higher education.",
    url: "https://www.ffa.org/participate/grants-and-scholarships/scholarships/",
    applicationUrl: "https://www.ffa.org/participate/grants-and-scholarships/scholarships/",
    scholarshipType: "both",
    scholarshipAmount: "$300–$22,000",
    scholarshipDeadline: "February 15",
    scholarshipSeason: "late_fall",
    gpaRequirement: "2.0+",
    minGpaDecimal: 2.0,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["FFA member", "Agricultural education student", "Min 2.0 GPA"],
    careerFields: ["Agriculture", "Environmental Science", "Food Science"],
    stateRestrictions: [],
    tags: ["agriculture", "FFA", "rural", "science"],
    category: "Agriculture",
  },
  {
    title: "CVS Health Foundation Scholarship",
    description: "Supports students pursuing healthcare and pharmacy-related degrees.",
    url: "https://cvshealth.com/social-responsibility/our-commitments/education",
    applicationUrl: "https://www.scholarshipamerica.org/cvshealthfoundation/",
    scholarshipType: "both",
    scholarshipAmount: "Varies",
    scholarshipDeadline: "Varies",
    scholarshipSeason: "early_spring",
    gpaRequirement: "2.5+",
    minGpaDecimal: 2.5,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Healthcare or pharmacy major", "Financial need", "Min 2.5 GPA", "Community service"],
    careerFields: ["Healthcare", "Pharmacy", "Medicine"],
    stateRestrictions: [],
    tags: ["healthcare", "pharmacy", "need-based"],
    category: "Healthcare",
  },
  {
    title: "Davidson Fellows Scholarship",
    description: "Recognizes students 18 and under who have completed significant projects that have the potential to benefit society.",
    url: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
    applicationUrl: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
    scholarshipType: "merit",
    scholarshipAmount: "$10,000–$50,000",
    scholarshipDeadline: "February",
    scholarshipSeason: "late_fall",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "high_school",
    firstGenFriendly: false,
    isRecurring: false,
    eligibilityCriteria: ["18 or younger", "US citizen or permanent resident", "Completed significant project", "Enrolled in college within 2 years"],
    careerFields: ["STEM", "Technology", "Arts", "Literature", "Philosophy"],
    stateRestrictions: [],
    tags: ["gifted", "project-based", "prestigious", "young-scholars"],
    category: "General",
  },
  {
    title: "Regeneron Science Talent Search",
    description: "The nation's oldest and most prestigious science and mathematics competition for high school seniors.",
    url: "https://www.societyforscience.org/regeneron-sts/",
    applicationUrl: "https://www.societyforscience.org/regeneron-sts/",
    scholarshipType: "merit",
    scholarshipAmount: "$25,000–$250,000",
    scholarshipDeadline: "November",
    scholarshipSeason: "early_fall",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "high_school",
    firstGenFriendly: false,
    isRecurring: false,
    eligibilityCriteria: ["High school senior", "US citizen or permanent resident", "Original independent science research", "STEM focus"],
    careerFields: ["STEM", "Research", "Science", "Mathematics"],
    stateRestrictions: [],
    tags: ["science", "research", "competition", "prestigious", "STEM"],
    category: "STEM",
  },
  {
    title: "AXA Achievement Scholarship",
    description: "Recognizes and rewards exceptional students who demonstrate outstanding achievement in their school and communities.",
    url: "https://us.axa.com/axa-foundation/scholarship.html",
    applicationUrl: "https://us.axa.com/axa-foundation/scholarship.html",
    scholarshipType: "merit",
    scholarshipAmount: "$10,000–$25,000",
    scholarshipDeadline: "December 15",
    scholarshipSeason: "late_fall",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "high_school",
    firstGenFriendly: false,
    isRecurring: false,
    eligibilityCriteria: ["High school senior", "US citizen or permanent resident", "Demonstrated achievement in school or community"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["achievement", "community-service", "leadership"],
    category: "General",
  },
  {
    title: "Army ROTC Scholarship",
    description: "Provides financial assistance to students who join the Army ROTC program at their college.",
    url: "https://www.goarmy.com/rotc/scholarships.html",
    applicationUrl: "https://www.goarmy.com/rotc/scholarships/high-school-scholarships.html",
    scholarshipType: "both",
    scholarshipAmount: "Full tuition + fees + $1,200/year",
    scholarshipDeadline: "November",
    scholarshipSeason: "early_fall",
    gpaRequirement: "2.5+",
    minGpaDecimal: 2.5,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["US citizen", "17–26 years old", "High school senior or grad", "Min 2.5 GPA", "Minimum SAT/ACT scores", "Physical fitness requirement"],
    careerFields: ["Military", "Leadership", "Public Service"],
    stateRestrictions: [],
    tags: ["military", "ROTC", "service-commitment", "leadership"],
    category: "Military",
  },
  {
    title: "Phi Theta Kappa Scholarship",
    description: "Supports community college students through scholarships at 4-year transfer institutions.",
    url: "https://www.ptk.org/scholarships/",
    applicationUrl: "https://www.ptk.org/scholarships/",
    scholarshipType: "merit",
    scholarshipAmount: "$1,000–Full scholarship",
    scholarshipDeadline: "Varies by partner institution",
    scholarshipSeason: "early_spring",
    gpaRequirement: "3.5+",
    minGpaDecimal: 3.5,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: false,
    eligibilityCriteria: ["PTK member", "Community college student", "Min 3.5 GPA", "Transferring to 4-year institution"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["community-college", "transfer", "PTK", "merit"],
    category: "General",
  },
  {
    title: "Doodle for Google Scholarship",
    description: "An annual competition inviting K-12 students to create a Google Doodle for a chance to win scholarships.",
    url: "https://doodles.google/doodle-for-google/",
    applicationUrl: "https://doodles.google/doodle-for-google/",
    scholarshipType: "merit",
    scholarshipAmount: "$30,000",
    scholarshipDeadline: "March",
    scholarshipSeason: "early_spring",
    gpaRequirement: "None",
    minGpaDecimal: null,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["K-12 student in US school", "Legal resident of US", "Compete art piece (doodle)", "No minimum GPA"],
    careerFields: ["Arts", "Technology", "Design"],
    stateRestrictions: [],
    tags: ["art", "design", "competition", "Google", "creative"],
    category: "Arts",
  },
  {
    title: "Jackie Robinson Foundation Scholarship",
    description: "Provides four-year scholarships to minority students who exhibit extraordinary leadership potential.",
    url: "https://jackierobinson.org/apply/",
    applicationUrl: "https://jackierobinson.org/apply/",
    scholarshipType: "both",
    scholarshipAmount: "Up to $30,000 (over 4 years)",
    scholarshipDeadline: "February 1",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Minority student", "High school senior", "US citizen", "Min 3.0 GPA", "Financial need", "Demonstrated leadership"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["minority", "leadership", "need-based", "sports", "community"],
    category: "General",
  },
  {
    title: "Amazon Future Engineer Scholarship",
    description: "Provides scholarships and internships to students who are pursuing CS degrees from underrepresented backgrounds.",
    url: "https://www.amazonfutureengineer.com/scholarships",
    applicationUrl: "https://www.amazonfutureengineer.com/scholarships",
    scholarshipType: "both",
    scholarshipAmount: "$40,000 + internship",
    scholarshipDeadline: "January",
    scholarshipSeason: "late_fall",
    gpaRequirement: "2.5+",
    minGpaDecimal: 2.5,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: false,
    eligibilityCriteria: ["High school senior", "Computer Science or related major", "Financial need", "Underrepresented background"],
    careerFields: ["Technology", "Computer Science", "Engineering"],
    stateRestrictions: [],
    tags: ["tech", "CS", "Amazon", "internship", "underrepresented"],
    category: "STEM",
  },
  {
    title: "Microsoft Scholarship Program",
    description: "Offers scholarships and paid internships to underrepresented students in computer science and related fields.",
    url: "https://careers.microsoft.com/us/en/usscholarshipprogram",
    applicationUrl: "https://careers.microsoft.com/us/en/usscholarshipprogram",
    scholarshipType: "merit",
    scholarshipAmount: "Up to $5,000",
    scholarshipDeadline: "February",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: false,
    eligibilityCriteria: ["Computer Science or STEM major", "Junior or senior undergrad", "Underrepresented group (women, Black, Hispanic, Native)", "Min 3.0 GPA"],
    careerFields: ["Technology", "Computer Science", "Engineering"],
    stateRestrictions: [],
    tags: ["tech", "Microsoft", "CS", "diversity"],
    category: "STEM",
  },
  {
    title: "Fulbright U.S. Student Program",
    description: "Provides grants for individually designed study/research projects or English Teaching Assistant programs.",
    url: "https://us.fulbrightonline.org",
    applicationUrl: "https://us.fulbrightonline.org/applicants/getting-started",
    scholarshipType: "merit",
    scholarshipAmount: "Full funding (varies by country)",
    scholarshipDeadline: "October (campus deadlines earlier)",
    scholarshipSeason: "early_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "graduate",
    firstGenFriendly: false,
    isRecurring: false,
    eligibilityCriteria: ["US citizen", "Bachelor's degree by start of grant", "Demonstrated leadership", "Interest in international study or research"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["international", "graduate", "prestigious", "research", "teaching"],
    category: "General",
  },
  {
    title: "Harry S. Truman Scholarship",
    description: "Recognizes students committed to careers in government or public service and who want to attend graduate school.",
    url: "https://www.truman.gov",
    applicationUrl: "https://www.truman.gov/are-you-candidate",
    scholarshipType: "merit",
    scholarshipAmount: "Up to $30,000",
    scholarshipDeadline: "February (institution deadline)",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "undergraduate",
    firstGenFriendly: false,
    isRecurring: false,
    eligibilityCriteria: ["Junior undergrad", "US citizen or US national", "Commitment to public service career", "Top of class"],
    careerFields: ["Public Service", "Government", "Law", "Policy"],
    stateRestrictions: [],
    tags: ["public-service", "government", "graduate-school", "prestigious"],
    category: "Public Service",
  },
  {
    title: "Udall Undergraduate Scholarship",
    description: "Supports college sophomores and juniors committed to careers related to the environment or Native American issues.",
    url: "https://www.udall.gov",
    applicationUrl: "https://www.udall.gov/OurPrograms/Scholarship/Scholarship.aspx",
    scholarshipType: "merit",
    scholarshipAmount: "Up to $7,000",
    scholarshipDeadline: "March (institution deadline)",
    scholarshipSeason: "early_spring",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "undergraduate",
    firstGenFriendly: false,
    isRecurring: false,
    eligibilityCriteria: ["Sophomore or junior undergrad", "US citizen, permanent resident, or DACA", "Major related to environment OR Native American/Alaska Native student"],
    careerFields: ["Environmental Science", "Public Policy", "Native American Studies"],
    stateRestrictions: [],
    tags: ["environment", "Native-American", "sustainability", "prestigious"],
    category: "Environmental",
  },
  {
    title: "Rotary Foundation Ambassadorial Scholarship",
    description: "Supports graduate students committed to promoting international goodwill and understanding.",
    url: "https://www.rotary.org/en/our-programs/scholarships",
    applicationUrl: "https://www.rotary.org/en/our-programs/scholarships",
    scholarshipType: "merit",
    scholarshipAmount: "Varies by club",
    scholarshipDeadline: "Varies by club",
    scholarshipSeason: "early_spring",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "graduate",
    firstGenFriendly: false,
    isRecurring: false,
    eligibilityCriteria: ["Bachelor's degree or equivalent", "Commitment to international understanding", "Community service record"],
    careerFields: ["International Relations", "Public Service", "Education"],
    stateRestrictions: [],
    tags: ["international", "community-service", "leadership", "graduate"],
    category: "General",
  },
  {
    title: "P.E.O. Program for Continuing Education",
    description: "Provides grants to women who need financial assistance to complete or re-enter an educational program.",
    url: "https://www.peointernational.org/about-peo-continuing-education-grant",
    applicationUrl: "https://www.peointernational.org/about-peo-continuing-education-grant",
    scholarshipType: "both",
    scholarshipAmount: "Up to $3,000",
    scholarshipDeadline: "Contact local chapter",
    scholarshipSeason: "early_spring",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: false,
    eligibilityCriteria: ["Women", "US or Canadian citizen", "Interrupted education for at least 24 months", "Financial need"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["women", "returning-adult", "continuing-education", "need-based"],
    category: "General",
  },
  {
    title: "National Society of Black Engineers (NSBE) Scholarship",
    description: "Provides scholarships to African American students pursuing engineering degrees.",
    url: "https://www.nsbe.org/Programs/Scholarships-and-Awards",
    applicationUrl: "https://www.nsbe.org/Programs/Scholarships-and-Awards",
    scholarshipType: "both",
    scholarshipAmount: "Varies",
    scholarshipDeadline: "February 15",
    scholarshipSeason: "late_fall",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["African American", "Engineering major", "NSBE member", "Min 3.0 GPA"],
    careerFields: ["Engineering", "STEM", "Technology"],
    stateRestrictions: [],
    tags: ["African-American", "engineering", "STEM", "NSBE"],
    category: "Engineering",
  },
  {
    title: "Society of Hispanic Professional Engineers (SHPE) Scholarship",
    description: "Supports Hispanic students pursuing STEM degrees through financial assistance and professional development.",
    url: "https://shpe.org/engage/scholarships/",
    applicationUrl: "https://shpe.org/engage/scholarships/",
    scholarshipType: "both",
    scholarshipAmount: "$1,000–$5,000",
    scholarshipDeadline: "April",
    scholarshipSeason: "early_spring",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "undergraduate",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["Hispanic heritage", "STEM major", "SHPE member or community involved", "Min 3.0 GPA"],
    careerFields: ["Engineering", "STEM", "Technology", "Science"],
    stateRestrictions: [],
    tags: ["Hispanic", "Latino", "STEM", "engineering"],
    category: "Engineering",
  },
  {
    title: "Creative Arts Scholarship (Scholastic Art & Writing Awards)",
    description: "Recognizes student achievement in creative arts through regional and national competitions with cash prizes.",
    url: "https://www.artandwriting.org",
    applicationUrl: "https://www.artandwriting.org/apply",
    scholarshipType: "merit",
    scholarshipAmount: "$1,000–$10,000",
    scholarshipDeadline: "December–January",
    scholarshipSeason: "late_fall",
    gpaRequirement: "None",
    minGpaDecimal: null,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["High school student (grades 7-12)", "Submission of original creative art or writing work"],
    careerFields: ["Arts", "Creative Writing", "Design", "Media"],
    stateRestrictions: [],
    tags: ["art", "writing", "creative", "competition"],
    category: "Arts",
  },
  {
    title: "Jack & Jill of America Foundation Scholarship",
    description: "Provides scholarships to African American students demonstrating academic achievement and community service.",
    url: "https://jackandjillfoundation.org/scholarships/",
    applicationUrl: "https://jackandjillfoundation.org/scholarships/",
    scholarshipType: "both",
    scholarshipAmount: "$1,500–$2,500",
    scholarshipDeadline: "March 1",
    scholarshipSeason: "early_spring",
    gpaRequirement: "3.0+",
    minGpaDecimal: 3.0,
    studentLevel: "high_school",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["African American", "High school senior", "Min 3.0 GPA", "Financial need", "Community service"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["African-American", "community-service", "need-based"],
    category: "General",
  },
  {
    title: "Sallie Mae Scholarship",
    description: "Provides scholarships to students with financial need who are pursuing higher education.",
    url: "https://www.salliemae.com/college-planning/scholarships/",
    applicationUrl: "https://www.salliemae.com/college-planning/scholarships/",
    scholarshipType: "both",
    scholarshipAmount: "$1,000–$5,000",
    scholarshipDeadline: "December",
    scholarshipSeason: "late_fall",
    gpaRequirement: "None specified",
    minGpaDecimal: null,
    studentLevel: "all",
    firstGenFriendly: true,
    isRecurring: true,
    eligibilityCriteria: ["US citizen or permanent resident", "Enrolled or planning to enroll in college", "Financial need"],
    careerFields: [],
    stateRestrictions: [],
    tags: ["accessible", "need-based", "general"],
    category: "General",
  },
];

// ─── Season Detection ─────────────────────────────────────────────────────────

export function detectSeasonFromDeadline(deadline: string): string {
  if (!deadline) return "early_fall";
  const lower = deadline.toLowerCase();
  const monthMatch = lower.match(
    /\b(january|february|march|april|may|june|july|august|september|october|november|december)\b/
  );
  if (!monthMatch) return "early_fall";
  const monthMap: Record<string, number> = {
    january: 1, february: 2, march: 3, april: 4, may: 5, june: 6,
    july: 7, august: 8, september: 9, october: 10, november: 11, december: 12,
  };
  const month = monthMap[monthMatch[1]];
  if (month >= 8 && month <= 10) return "early_fall";
  if (month >= 11 || month <= 1) return "late_fall";
  if (month >= 2 && month <= 5) return "early_spring";
  return "late_spring";
}

// ─── URL Validator ────────────────────────────────────────────────────────────

async function validateUrl(url: string): Promise<"active" | "broken"> {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10000);
    const response = await fetch(url, {
      method: "HEAD",
      signal: controller.signal,
      redirect: "follow",
      headers: { "User-Agent": "LYS-ScholarshipBot/1.0 (link-validator)" },
    });
    clearTimeout(timeout);
    if (response.status === 404 || response.status === 410 || response.status === 451) {
      return "broken";
    }
    return "active";
  } catch {
    return "broken";
  }
}

// ─── Seed Scholarships ────────────────────────────────────────────────────────

async function seedScholarships(): Promise<number> {
  let newCount = 0;
  const SYSTEM_USER = "system";

  for (const s of SEED_SCHOLARSHIPS) {
    // Check if already exists by title to avoid duplicates
    const existing = await db
      .select({ id: knowResources.id })
      .from(knowResources)
      .where(eq(knowResources.title, s.title))
      .limit(1);

    if (existing.length > 0) continue;

    await db.insert(knowResources).values({
      title: s.title,
      description: s.description,
      resourceType: "scholarship",
      category: s.category,
      url: s.url,
      applicationUrl: s.applicationUrl,
      scholarshipType: s.scholarshipType,
      scholarshipAmount: s.scholarshipAmount,
      scholarshipDeadline: s.scholarshipDeadline,
      scholarshipSeason: s.scholarshipSeason,
      gpaRequirement: s.gpaRequirement,
      minGpaDecimal: s.minGpaDecimal ?? undefined,
      studentLevel: s.studentLevel,
      firstGenFriendly: s.firstGenFriendly,
      isRecurring: s.isRecurring,
      eligibilityCriteria: s.eligibilityCriteria,
      careerFields: s.careerFields,
      stateRestrictions: s.stateRestrictions,
      tags: s.tags,
      targetAudience: ["students"],
      autoImported: true,
      urlStatus: "unknown",
      isActive: true,
      featured: false,
      sortOrder: 0,
      createdBy: SYSTEM_USER,
    });
    newCount++;
  }

  return newCount;
}

// ─── Link Validation Pass ─────────────────────────────────────────────────────

async function validateExistingScholarships(): Promise<{ validated: number; deactivated: number }> {
  // Find scholarships that haven't been validated in the last 30 days, or never validated
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);

  const toValidate = await db
    .select({ id: knowResources.id, url: knowResources.url, applicationUrl: knowResources.applicationUrl })
    .from(knowResources)
    .where(
      and(
        eq(knowResources.resourceType, "scholarship"),
        eq(knowResources.isActive, true),
        or(
          isNull(knowResources.lastValidatedAt),
          lt(knowResources.lastValidatedAt, thirtyDaysAgo)
        )
      )
    );

  let validated = 0;
  let deactivated = 0;

  for (const resource of toValidate) {
    const targetUrl = resource.applicationUrl || resource.url;
    if (!targetUrl) {
      validated++;
      continue;
    }

    const status = await validateUrl(targetUrl);
    await db
      .update(knowResources)
      .set({
        urlStatus: status,
        lastValidatedAt: new Date(),
        isActive: status === "active" ? true : false,
        updatedBy: "system",
        updatedAt: new Date(),
      })
      .where(eq(knowResources.id, resource.id));

    if (status === "broken") deactivated++;
    validated++;

    // Brief pause between requests to be polite
    await new Promise((r) => setTimeout(r, 500));
  }

  return { validated, deactivated };
}

// ─── Full Sync ────────────────────────────────────────────────────────────────

export async function runScholarshipSync(type: "full" | "validation" | "import" = "full"): Promise<void> {
  console.log(`[ScholarshipSync] Starting ${type} sync...`);

  const [logEntry] = await db
    .insert(scholarshipSyncLog)
    .values({ syncType: type, status: "running" })
    .returning();

  let newCount = 0;
  let deactivatedCount = 0;
  let validatedCount = 0;
  let errorCount = 0;

  try {
    if (type === "full" || type === "import") {
      newCount = await seedScholarships();
      console.log(`[ScholarshipSync] Seeded ${newCount} new scholarships`);
    }

    if (type === "full" || type === "validation") {
      const { validated, deactivated } = await validateExistingScholarships();
      validatedCount = validated;
      deactivatedCount = deactivated;
      console.log(`[ScholarshipSync] Validated ${validated}, deactivated ${deactivated}`);
    }

    await db
      .update(scholarshipSyncLog)
      .set({
        status: "completed",
        newCount,
        deactivatedCount,
        validatedCount,
        errorCount,
        notes: `Sync completed successfully`,
        completedAt: new Date(),
      })
      .where(eq(scholarshipSyncLog.id, logEntry.id));

    console.log(`[ScholarshipSync] Sync complete — new: ${newCount}, validated: ${validatedCount}, deactivated: ${deactivatedCount}`);
  } catch (err: any) {
    errorCount++;
    console.error("[ScholarshipSync] Sync error:", err);
    await db
      .update(scholarshipSyncLog)
      .set({
        status: "failed",
        errorCount,
        notes: err?.message || "Unknown error",
        completedAt: new Date(),
      })
      .where(eq(scholarshipSyncLog.id, logEntry.id));
  }
}

// ─── Monthly Scheduler ────────────────────────────────────────────────────────
// Uses an hourly check pattern (like the BLS scheduler) to avoid 32-bit
// setTimeout overflow on durations > ~24.8 days.

const THIRTY_DAYS_MS = 30 * 24 * 60 * 60 * 1000;
let lastFullSyncAt: Date | null = null;

export async function startScholarshipScheduler(): Promise<void> {
  console.log("Starting scholarship scheduler (monthly sync)");

  // Run initial seed on startup (import only, quick)
  try {
    await runScholarshipSync("import");
    lastFullSyncAt = new Date();
  } catch (err) {
    console.error("[ScholarshipSync] Initial seed failed:", err);
  }

  // Check every hour whether 30 days have elapsed; if so, run a full sync
  setInterval(async () => {
    if (!lastFullSyncAt || Date.now() - lastFullSyncAt.getTime() >= THIRTY_DAYS_MS) {
      try {
        await runScholarshipSync("full");
        lastFullSyncAt = new Date();
      } catch (err) {
        console.error("[ScholarshipSync] Monthly sync failed:", err);
      }
    }
  }, 60 * 60 * 1000); // check every hour
}
